Running tests on a test flinger device
Loading environment variables
Using environment file: tf_snapd_db
Deleting test flinger data
Creating job for snapd using a device
Running testflinger client
Submitting job to testflinger
JOB_ID: ac71f872-65ea-4eae-9dc0-448ec260f671
Print job: /var/snap/testflinger-cli/current/job.yaml 
job_queue: dragonboard
global_timeout: 36000
provision_data:
    channel: beta
test_data:
    test_cmds: |
        #!/bin/bash
        sudo apt update || ps aux | grep apt
        sudo apt install -y git curl sshpass
        git clone https://github.com/sergiocazzolato/snappy-qa-jobs.git
        (cd snappy-qa-jobs && git checkout master)
        git clone https://git.launchpad.net/snapd-vendor snapd
        (cd snapd && git checkout master)
        . snapd/tests/lib/external/prepare-ssh.sh "{device_ip}" "22" "ubuntu"
        . snappy-qa-jobs/scripts/utils/register_device.sh "{device_ip}" "22" "test" "ubuntu" "sergiocazzolato@yahoo.com.ar"
        . snappy-qa-jobs/scripts/utils/refresh_core.sh "{device_ip}" "22" "test" "ubuntu" "beta" "edge"
        . snappy-qa-jobs/scripts/utils/run_setup.sh "{device_ip}" "22" "test" "ubuntu" ""
        . snappy-qa-jobs/scripts/utils/get_spread.sh
        . snappy-qa-jobs/scripts/utils/run_spread.sh "{device_ip}" "22" "snapd" "external:ubuntu-core-16-arm-64:tests/" "" "tests/main/auto-refresh,tests/main/failover,tests/main/ubuntu-core-services"
Showing job data
This job is currently waiting on a node to become available. You will see no further output until the job starts running.
*******************************************
* Starting setup phase on dragonboard-003 *

*******************************************

Cleaning up container if it exists...
Error response from daemon: No such container: dragonboard003

***********************************************
* Starting provision phase on dragonboard-003 *

***********************************************
Install python-logstash if you want to use logstash logging
2018-01-18 07:52:13,767 dragonboard_003 INFO: BEGIN provision
2018-01-18 07:52:13,767 dragonboard_003 INFO: Booting Master Image
2018-01-18 07:52:13,767 dragonboard_003 INFO: Making sure the master image is booted
2018-01-18 07:52:13,767 dragonboard_003 INFO: Checking if test image booted.
2018-01-18 07:52:13,993 dragonboard_003 INFO: Checking if master image booted.
2018-01-18 07:53:35,607 dragonboard_003 INFO: Flashing Test Image
2018-01-18 07:53:36,031 dragonboard_003 INFO: Running: nc 10.101.50.22 33183| gunzip| sudo dd of=/dev/mmcblk1 bs=16M
2018-01-18 08:23:36,135 dragonboard_003 ERROR: Failed to write image, cleaning up...

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/__init__.py", line 233, in serve_file
    client.send(data)
TimeoutError: [Errno 110] Connection timed out
2018-01-18 08:23:39,135 dragonboard_003 ERROR: exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 33183| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 261, in flash_test_image
    self._run_control(cmd, timeout=1800)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 700, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 33183| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 374, in provision
    self.flash_test_image(server_ip, server_port)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 263, in flash_test_image
    raise ProvisioningError("timeout reached while flashing image!")
devices.ProvisioningError: timeout reached while flashing image!
Traceback (most recent call last):
  File "/usr/lib/python3.5/subprocess.py", line 695, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 33183| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 261, in flash_test_image
    self._run_control(cmd, timeout=1800)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 700, in run
    stderr=stderr)
subprocess.TimeoutExpired: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.13', 'nc 10.101.50.22 33183| gunzip| sudo dd of=/dev/mmcblk1 bs=16M']' timed out after 1800 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard003/env/bin/snappy-device-agent", line 4, in <module>
    __import__('pkg_resources').run_script('snappy-device-agents==0.0.1', 'snappy-device-agent')
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/EGG-INFO/scripts/snappy-device-agent", line 25, in <module>
    main()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 75, in main
    Agent().main()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 71, in main
    return AgentCommandRecipe(self).main(argv, exit)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/recipes/__init__.py", line 119, in main
    retval = bowl.eat(argv)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 254, in eat
    self._dispatch_failed()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 310, in _dispatch_failed
    ingredient.dispatch_failed(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 374, in provision
    self.flash_test_image(server_ip, server_port)
  File "/srv/testflinger-agent/dragonboard003/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 263, in flash_test_image
    raise ProvisioningError("timeout reached while flashing image!")
devices.ProvisioningError: timeout reached while flashing image!
complete
