Running tests on a test flinger device
Loading environment variables
Using environment file: tf_snapd_cm3_refresh
Deleting test flinger data
Creating job for snapd using a device
Running testflinger client
Submitting job to testflinger
JOB_ID: ea1f546f-065b-4c09-bb9d-0b7d5af4f935
Print job: /var/snap/testflinger-cli/current/job.yaml 
job_queue: dragonboard
global_timeout: 36000
provision_data:
    channel: stable
test_data:
    test_cmds: |
        #!/bin/bash
        sudo apt update || ps aux | grep apt
        sudo apt install -y git curl sshpass
        git clone https://github.com/sergiocazzolato/snappy-qa-jobs.git
        (cd snappy-qa-jobs && git checkout master)
        git clone https://git.launchpad.net/snapd-vendor snapd
        (cd snapd && git checkout master)
        . snapd/tests/lib/external/prepare-ssh.sh "{device_ip}" "22" "ubuntu"
        . snappy-qa-jobs/scripts/utils/register_device.sh "{device_ip}" "22" "test" "ubuntu" "sergiocazzolato@yahoo.com.ar"
        . snappy-qa-jobs/scripts/utils/refresh_core.sh "{device_ip}" "22" "test" "ubuntu" "stable" "edge"
        . snappy-qa-jobs/scripts/utils/run_setup.sh "{device_ip}" "22" "test" "ubuntu" ""
        . snappy-qa-jobs/scripts/utils/get_spread.sh
        . snappy-qa-jobs/scripts/utils/run_spread.sh "{device_ip}" "22" "snapd" "external:ubuntu-core-16-arm-64:tests/" "" "tests/main/auto-refresh,tests/main/interfaces-content" "-v"
Showing job data
This job is currently waiting on a node to become available. You will see no further output until the job starts running.
*******************************************

* Starting setup phase on dragonboard-004 *

*******************************************

Cleaning up container if it exists...
Error response from daemon: No such container: dragonboard004

***********************************************

* Starting provision phase on dragonboard-004 *

***********************************************
Install python-logstash if you want to use logstash logging
2018-05-17 04:41:21,792 dragonboard_004 INFO: BEGIN provision
2018-05-17 04:41:21,792 dragonboard_004 INFO: Booting Master Image
2018-05-17 04:41:21,792 dragonboard_004 INFO: Making sure the master image is booted
2018-05-17 04:41:21,792 dragonboard_004 INFO: Checking if test image booted.
2018-05-17 04:41:22,048 dragonboard_004 INFO: Checking if master image booted.
2018-05-17 04:43:28,186 dragonboard_004 INFO: Flashing Test Image
2018-05-17 04:43:28,620 dragonboard_004 INFO: Running: nc 10.101.50.22 37628| gunzip| sudo dd of=/dev/mmcblk1 bs=16M
2018-05-17 04:55:12,369 dragonboard_004 INFO: Creating Test User

2018-05-17 04:55:14,587 dragonboard_004 ERROR: Failed to write image, cleaning up...
2018-05-17 04:55:16,207 dragonboard_004 ERROR: exception
Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.14', 'sudo mount /dev/mmcblk1p9 /mnt']' returned non-zero exit status 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 282, in mount_writable_partition
    self.config['snappy_writable_partition']))
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 61, in _run_control
    raise ProvisioningError(e.output)
devices.ProvisioningError: b"Warning: Permanently added '10.101.51.14' (ECDSA) to the list of known hosts.\r\nmount: wrong fs type, bad option, bad superblock on /dev/mmcblk1p9,\n       missing codepage or helper program, or other error\n\n       In some cases useful info is found in syslog - try\n       dmesg | tail or so.\n"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 377, in provision
    self.create_extrausers()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 291, in create_extrausers
    self.mount_writable_partition()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 287, in mount_writable_partition
    raise ProvisioningError(err)
devices.ProvisioningError: Error mounting writable partition on test image /dev/mmcblk1p9. Check device configuration
Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 59, in _run_control
    cmd, stderr=subprocess.STDOUT, timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ssh', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', 'linaro@10.101.51.14', 'sudo mount /dev/mmcblk1p9 /mnt']' returned non-zero exit status 32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 282, in mount_writable_partition
    self.config['snappy_writable_partition']))
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 61, in _run_control
    raise ProvisioningError(e.output)
devices.ProvisioningError: b"Warning: Permanently added '10.101.51.14' (ECDSA) to the list of known hosts.\r\nmount: wrong fs type, bad option, bad superblock on /dev/mmcblk1p9,\n       missing codepage or helper program, or other error\n\n       In some cases useful info is found in syslog - try\n       dmesg | tail or so.\n"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/testflinger-agent/dragonboard004/env/bin/snappy-device-agent", line 4, in <module>
    __import__('pkg_resources').run_script('snappy-device-agents==0.0.1', 'snappy-device-agent')
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/EGG-INFO/scripts/snappy-device-agent", line 25, in <module>
    main()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 75, in main
    Agent().main()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/snappy_device_agents/cmd.py", line 71, in main
    return AgentCommandRecipe(self).main(argv, exit)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/recipes/__init__.py", line 119, in main
    retval = bowl.eat(argv)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 254, in eat
    self._dispatch_failed()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 310, in _dispatch_failed
    ingredient.dispatch_failed(self.context)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 248, in eat
    return self._dispatch()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/core.py", line 298, in _dispatch
    result = ingredient.dispatch(self.context)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 152, in dispatch
    return self._dispatch(context, 0)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 179, in _dispatch
    return self._dispatch_None(context, level, retval, command)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 208, in _dispatch_None
    return self._dispatch(context, level + 1)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/guacamole-0.9.2-py3.5.egg/guacamole/ingredients/cmdtree.py", line 165, in _dispatch
    retval = command.invoked(context)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/__init__.py", line 37, in wrapper
    return func(*args, **kwargs)
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/__init__.py", line 44, in invoked
    device.provision()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 377, in provision
    self.create_extrausers()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 291, in create_extrausers
    self.mount_writable_partition()
  File "/srv/testflinger-agent/dragonboard004/env/lib/python3.5/site-packages/snappy_device_agents-0.0.1-py3.5.egg/devices/dragonboard/dragonboard.py", line 287, in mount_writable_partition
    raise ProvisioningError(err)
devices.ProvisioningError: Error mounting writable partition on test image /dev/mmcblk1p9. Check device configuration
complete
